#!/usr/bin/env bash
# This script should be used instead of Concourse "fly" cli in order to deploy
# the pipeline. It simply calls "gomplate" to render the final pipeline definition.
# It delegated all other options to the real "fly".
#
# E.g. ./fly -t target set-pipeline

set -o errtrace -o errexit -o nounset -o pipefail

if ! type -t gomplate >/dev/null ; then
  echo "gomplate missing. Follow the instructions in https://docs.gomplate.ca/installing/ and install it first."
  exit 1
fi

command=( gomplate --verbose --file pipeline.yaml.gomplate )
pipeline="eirinix"
if [[ -r config.yaml ]]; then
  command+=(--context ".=config.yaml")
  pipeline="${USER}-${pipeline}"
fi

"${command[@]}" >/dev/null # Check for template rendering failures
fly "${@}" --config <("${command[@]}") --pipeline "${pipeline}"
